--start
--DB CREATION SCRIPTS OFTER BEGIN WITH DROP STATEMENTS
--AVOIDS CLASSES WITH EXISTING TABLE

DROP TABLE BEAR;
/
DROP TABLE BEAR_TYPE;
/
DROP TABLE CAVE;
/
DROP TABLE BEEHIVE;
/
DROP TABLE BEAR_BEEHIVE;


--TABLE CREATION BEGINS HERE
CREATE TABLE BEAR_TYPE(
    BEAR_TYPE_ID INTEGER PRIMARY KEY,
    BEAR_TYPE_NAME varchar2(100)
    );
/
Create table CAVE
(
    CAVE_ID INTEGER PRIMARY KEY,
    CAVE_NAME varchar2(100),
    MAX_BEARS INTEGER DEFAULT 4
    );
/
create table BEAR
(
    BEAR_ID INTEGER PRIMARY KEY,
    BEAR_NAME VARCHAR2(100),
    BIRTHDATE DATE,
    WEIGHT  NUMBER(6,2) DEFAULT 200.00,
    BEAR_TYPE_ID INTEGER NOT NULL, --NOT NULL CONSTRAINT TO THIS COLUMN, FOREIGN KEY
    CAVE_ID INTEGER -- WILL BE A NULLABLE FOREIGN KEY
    );
/
create table BEEHIVE
(
    BEEHIVE_ID INTEGER PRIMARY KEY,
    HONEY_AMY NUMBER(5,2) DEFAULT 75.00
    );
/
create table BEAR_BEEHIVE
(
    BEAR_ID INTEGER,
    BEEHIVE_ID INTEGER,
    PRIMARY KEY(BEAR_ID, BEEHIVE_ID)
    );
/



