INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (1,'Zi Feng');
INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (2,'Mohammad');
INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (3,'Steven');
INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (4,'Caleb');
INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (5,'Anon');

--INSERT INTO STUDENT (NAME) VALUES ('Zi Feng');
--INSERT INTO STUDENT (NAME) VALUES ('Mohammad');
--INSERT INTO STUDENT (NAME) VALUES ('Steven');
--INSERT INTO STUDENT (NAME) VALUES ('Caleb');
--INSERT INTO STUDENT (NAME) VALUES ('Anon');
COMMIT;