INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (1,'Zi Feng');
INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (2,'Mohammad');
INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (3,'Steven');
INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (4,'Caleb');
INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES (5,'Anon');

INSERT INTO COURSE (COURSE_ID,COURSE_NAME) VALUES (1,'Programming');
INSERT INTO COURSE (COURSE_ID,COURSE_NAME) VALUES (2,'Art');
INSERT INTO STUDENT_COURSE ( COURSE_ID, STUDENT_ID) VALUES (1,1);
INSERT INTO STUDENT_COURSE ( COURSE_ID, STUDENT_ID) VALUES (2,1);
INSERT INTO STUDENT_COURSE ( COURSE_ID, STUDENT_ID) VALUES (1,2);
INSERT INTO STUDENT_COURSE ( COURSE_ID, STUDENT_ID) VALUES (2,3);
INSERT INTO STUDENT_COURSE ( COURSE_ID, STUDENT_ID) VALUES (1,4);
INSERT INTO STUDENT_COURSE ( COURSE_ID, STUDENT_ID) VALUES (2,5);
--INSERT INTO STUDENT (NAME) VALUES ('Zi Feng');
--INSERT INTO STUDENT (NAME) VALUES ('Mohammad');
--INSERT INTO STUDENT (NAME) VALUES ('Steven');
--INSERT INTO STUDENT (NAME) VALUES ('Caleb');
--INSERT INTO STUDENT (NAME) VALUES ('Anon');


COMMIT;